



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aaryan
 */
import java.awt.Color;
import home.Home;
import home.admin_home;
import java.io.DataInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.Statement;
import signup.SignUp;
import java.sql.*;
import java.lang.*;
import java.security.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        Username_text_field.setBackground(new Color(0,0,0,64));
        Password_text_field.setBackground(new Color(0,0,0,64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        Username_label = new javax.swing.JLabel();
        Password_text_field = new javax.swing.JPasswordField();
        Username_text_field = new javax.swing.JTextField();
        Login_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Sign_up_button = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password_label.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        Password_label.setForeground(new java.awt.Color(253, 211, 29));
        Password_label.setText("Password");
        getContentPane().add(Password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 190, 50));

        Username_label.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        Username_label.setForeground(new java.awt.Color(253, 211, 29));
        Username_label.setText("Username");
        getContentPane().add(Username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 190, 50));

        Password_text_field.setBackground(new java.awt.Color(255, 255, 255));
        Password_text_field.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Password_text_field.setForeground(new java.awt.Color(247, 103, 103));
        Password_text_field.setToolTipText("Enter your password");
        Password_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_text_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(Password_text_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 230, 29));

        Username_text_field.setBackground(new java.awt.Color(217, 202, 189));
        Username_text_field.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Username_text_field.setForeground(new java.awt.Color(247, 103, 103));
        Username_text_field.setToolTipText("Enter your username");
        Username_text_field.setOpaque(false);
        Username_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_text_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(Username_text_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 230, 29));

        Login_button.setBackground(new java.awt.Color(4, 4, 1));
        Login_button.setFont(new java.awt.Font("TlwgMono", 1, 15)); // NOI18N
        Login_button.setForeground(new java.awt.Color(230, 135, 135));
        Login_button.setText("Login");
        Login_button.setToolTipText("Login");
        Login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 240, 40));

        jLabel1.setBackground(new java.awt.Color(244, 31, 31));
        jLabel1.setFont(new java.awt.Font("Waree", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 79, 72));
        jLabel1.setText("New User?, then");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 190, 50));

        Sign_up_button.setBackground(new java.awt.Color(198, 198, 52));
        Sign_up_button.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        Sign_up_button.setForeground(new java.awt.Color(37, 57, 255));
        Sign_up_button.setText("Sign Up");
        Sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_up_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Sign_up_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 240, 31));

        Title.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(160, 255, 66));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("DIGISIGN");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_up_buttonActionPerformed
        // TODO add your handling code here:
        SignUp su = new SignUp();
    	su.setVisible(true);
    }//GEN-LAST:event_Sign_up_buttonActionPerformed

    private void Login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_buttonActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/login","root", "echostorme!@#");
            Statement stmt = con.createStatement();
            String a = Username_text_field.getText();
            char[] x = Password_text_field.getPassword();
            String b = String.valueOf(x);


            ResultSet rs = stmt.executeQuery("select * from user_login where uid =" + '"' + a + '"');
            if (!rs.isBeforeFirst())
            {
                    JOptionPane.showMessageDialog(null,"No Such User Registered");

            }
            else
            {
                    rs.next();
                    //System.out.println(a + " " + rs.getString(1) + " " + b + " " + rs.getString(2));
                    if((a.equals(rs.getString(1))) && (b.equals(rs.getString(2))))
                    {
                            JOptionPane.showMessageDialog(null,"Login Success");
                            new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {

                            ServerSocket serverSocket = null;
                            String str1 = null;

                            try {
                                serverSocket = new ServerSocket(4444);
                            } catch (IOException ex) {
                                System.out.println("Can't setup server on this port number. ");
                            }

                            Socket socket = null;
                            InputStream in = null;
                            OutputStream out = null;
                            while(true)
                            {
                            try {
                                socket = serverSocket.accept();
                            } catch (IOException ex) {
                                System.out.println("Can't accept client connection. ");
                                    JOptionPane.showMessageDialog(null,"Connection Error!");

                            }

                            try {
                                DataInputStream dis = new DataInputStream(socket.getInputStream());
                                str1 = (String)dis.readUTF();
                            } catch (Exception e)
                            {
                                System.out.println(e);
                            }


                            try {
                                in = socket.getInputStream();
                            } catch (IOException ex) {
                                System.out.println("Can't get socket input stream. ");
                                    JOptionPane.showMessageDialog(null,"Connection Error!");

                            }

                            try {
                                String name = str1;
                                out = new FileOutputStream(name);
                            } catch (Exception ex) {
                                System.out.println("Exception occured: " + ex);
                                    JOptionPane.showMessageDialog(null,"Exception Occurred!");

                            }

                            byte[] bytes = new byte[16*1024];

                            int count;
                            while ((count = in.read(bytes)) > 0) {
                                out.write(bytes, 0, count);
                            }
                            JOptionPane.showMessageDialog(null,"File Successfully Received!");
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null,"Error");
                        }
                    }
                }).start();

                            if (a.equals("admin"))
                            {
                                    admin_home am = new admin_home();
                                    am.setVisible(true);

                            }
                            else
                            {
                                    Home home = new Home();
                                    home.setVisible(true);}}
                    else
                    {
                            JOptionPane.showMessageDialog(null,"Login Failed");
                    }
                    con.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Login_buttonActionPerformed

    private void Password_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_text_fieldActionPerformed

    private void Username_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_text_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_button;
    private javax.swing.JLabel Password_label;
    private javax.swing.JPasswordField Password_text_field;
    private javax.swing.JButton Sign_up_button;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Username_label;
    private javax.swing.JTextField Username_text_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
