/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aaryan
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup_title = new javax.swing.JLabel();
        signup_ip_field = new javax.swing.JTextField();
        signup_ip_label = new javax.swing.JLabel();
        signup_username_field = new javax.swing.JTextField();
        signup_username_label = new javax.swing.JLabel();
        signup_password_label = new javax.swing.JLabel();
        signup_password_field = new javax.swing.JTextField();
        signup_submit_button = new javax.swing.JButton();
        signup_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup_title.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        signup_title.setForeground(new java.awt.Color(105, 245, 30));
        signup_title.setText("Sign Up for a secure data transfer experience!");
        getContentPane().add(signup_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 95));

        signup_ip_field.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        signup_ip_field.setForeground(new java.awt.Color(235, 215, 21));
        signup_ip_field.setToolTipText("Enter  your IP address");
        signup_ip_field.setBackground(new java.awt.Color(0,0,0,64));
        signup_ip_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_ip_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(signup_ip_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 290, 40));

        signup_ip_label.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        signup_ip_label.setForeground(new java.awt.Color(241, 190, 245));
        signup_ip_label.setText("Enter your IP :");
        getContentPane().add(signup_ip_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 190, 40));

        signup_username_field.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        signup_username_field.setForeground(new java.awt.Color(235, 215, 21));
        signup_username_field.setToolTipText("Enter your username");
        signup_username_field.setBackground(new java.awt.Color(0,0,0,64));
        signup_username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_username_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(signup_username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 290, 40));

        signup_username_label.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        signup_username_label.setForeground(new java.awt.Color(241, 190, 245));
        signup_username_label.setText("Enter your Username :");
        getContentPane().add(signup_username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 300, 40));

        signup_password_label.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        signup_password_label.setForeground(new java.awt.Color(241, 190, 245));
        signup_password_label.setText("Enter your Password :");
        getContentPane().add(signup_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 280, 40));

        signup_password_field.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        signup_password_field.setForeground(new java.awt.Color(235, 215, 21));
        signup_password_field.setToolTipText("Enter your password");
        signup_password_field.setBackground(new java.awt.Color(0,0,0,64));
        signup_password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_password_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(signup_password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 290, 40));

        signup_submit_button.setBackground(new java.awt.Color(91, 88, 102));
        signup_submit_button.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        signup_submit_button.setForeground(new java.awt.Color(175, 211, 223));
        signup_submit_button.setText("Submit Details");
        signup_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_submit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(signup_submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 210, 50));

        signup_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup_background.jpg"))); // NOI18N
        getContentPane().add(signup_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signup_ip_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_ip_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_ip_fieldActionPerformed

    private void signup_username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_username_fieldActionPerformed

    private void signup_password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_password_fieldActionPerformed

    private void signup_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_submit_buttonActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/login","root", "echostorme!@#");
            Statement stmt = con.createStatement();
            String a = signup_username_field.getText();
            String b = signup_password_field.getText();

            String c = signup_ip_field.getText();
            ResultSet rs = stmt.executeQuery("select * from user_login where uid =" + '"' + a + '"');
            if (!rs.isBeforeFirst() ) {


                stmt.executeUpdate("INSERT INTO user_login VALUES(" + '"' + a + '"' + ',' + '"' + b + '"' + ',' + '"' + c + '"' + ')');
                JOptionPane.showMessageDialog(null,"Registration Successful!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"This username is already chosen!");
            }
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signup_submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel signup_background;
    private javax.swing.JTextField signup_ip_field;
    private javax.swing.JLabel signup_ip_label;
    private javax.swing.JTextField signup_password_field;
    private javax.swing.JLabel signup_password_label;
    private javax.swing.JButton signup_submit_button;
    private javax.swing.JLabel signup_title;
    private javax.swing.JTextField signup_username_field;
    private javax.swing.JLabel signup_username_label;
    // End of variables declaration//GEN-END:variables
}
